#!/bin/bash
# v4 band top-up (make_ablation_v4.py).
set -eo pipefail
cd "$(dirname "$0")/.."
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_full_g005.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_full_g008.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_full_g012.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_full_g020.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_full_g007.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_full_g010.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_bias0_g005.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_bias0_g008.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_bias0_g012.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_bias0_g020.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_bias0_g007.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_bias0_g010.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_nosyn_g005.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_nosyn_g008.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_nosyn_g012.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_nosyn_g020.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_nosyn_g007.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_nosyn_g010.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_both_g005.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_both_g008.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_both_g012.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_both_g020.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_both_g007.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_both_g010.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_full10k_g005.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_full10k_g008.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_full10k_g012.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_full10k_g020.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_full10k_g007.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_full10k_g010.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_bias010k_g005.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_bias010k_g008.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_bias010k_g012.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_bias010k_g020.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_bias010k_g007.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_bias010k_g010.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_nosyn10k_g005.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_nosyn10k_g008.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_nosyn10k_g012.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_nosyn10k_g020.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_nosyn10k_g007.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_nosyn10k_g010.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_both10k_g005.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_both10k_g008.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_both10k_g012.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_both10k_g020.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_both10k_g007.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_both10k_g010.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_full1k_g005.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_full1k_g008.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_full1k_g012.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_full1k_g020.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_full1k_g007.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_full1k_g010.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_bias01k_g005.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_bias01k_g008.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_bias01k_g012.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_bias01k_g020.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_bias01k_g007.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_bias01k_g010.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_nosyn1k_g005.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_nosyn1k_g008.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_nosyn1k_g012.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_nosyn1k_g020.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_nosyn1k_g007.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_nosyn1k_g010.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_both1k_g005.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_both1k_g008.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_both1k_g012.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_both1k_g020.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_both1k_g007.sh
sbatch --parsable scripts/motif_check/run_motif_check_ablv4_both1k_g010.sh
